# Generated by Django 5.2 on 2025-04-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, default=0, null=True)),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('USER', 'Foydalanuvchi')], default='USER', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_number', models.IntegerField(default=0)),
                ('video_title', models.CharField(max_length=255)),
                ('video_id', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
