# Generated by Django 5.2 on 2025-04-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_magicword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelstosubscribe',
            name='name',
        ),
    ]
