# Generated by Django 5.2 on 2025-04-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_channelstosubscribe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelstosubscribe',
            name='link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
